### ISSUE TITLE
Run with Docker on Windows 10

### ISSUE THREAD

**Issue by MikeWise2718** [monsta-hd/boltzmann-machines#2]
As far as I can tell from the instructions, this requires nvidia-docker to run with docker, and nvidia-docker does not run on Windows 10 due to lack of GPU passthrough in that OS (seems like it might work on Windows 2016 Server though). But there is no mention of this anywhere. It seems it should work in a non-GPU configuration, which would suffice for learning purposes.

So is nvidia-docker a requirement, or is there some undocumented way to get this to work with docker on Windows 10? Without GPU support?

**Comment by monsta-hd** [comment]
You can adapt regular [Dockerfile](https://github.com/monsta-hd/boltzmann-machines/blob/master/Dockerfile) (without nvidia-docker) for Windows together with installing `tensorflow` instead of `tensorflow-gpu` (see requirements.txt).
