### ISSUE TITLE
Fix python3 batch_iter or use tensorflow data batchsize generator

### ISSUE THREAD

**Issue by SrMouraSilva** [monsta-hd/boltzmann-machines#7]
utils.py Line 37
```
# Use // instead /
n_batches = N / batch_size + (N % batch_size > 0)
```
Python 2: float / int -> int
Python 3: float / int -> float
Python 3: float // int -> int

`use tensorflow data batchsize generator`

I will add information later

**Comment by monsta-hd** [comment]
Thanks for spotting.
If you find more bugs please add info or perhaps open a PR.
I actually plan to rewrite many things better when I have a bit more spare time.

**Comment by SrMouraSilva** [comment]
Hello, Yelysei Bondarenko

I'm working with RBM in master degree. My [current implementation](https://github.com/SrMouraSilva/RBM) in tensorflow might have some problems. I was testing on yours.

There is the possibility that I end up migrating to your implementation. But I need to work with [RBMCF](https://www.cs.toronto.edu/~rsalakhu/papers/rbmcf.pdf) and Conditional RBM. I'm not sure how to do it properly.

Anyway, I promise to make this merge request :D

---

A question. How to
> configure metrics to display during learning (which ones, frequency, format etc.)
?

**Comment by monsta-hd** [comment]
Please have a look here: https://github.com/monsta-hd/boltzmann-machines/blob/master/boltzmann_machines/rbm/base_rbm.py#L53-L72
